/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MarketRouteImport } from './routes/market'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsIdRouteImport } from './routes/teams.$id'
import { Route as LegalInfoRouteImport } from './routes/legal.info'
import { Route as LegalDocRouteImport } from './routes/legal.$doc'
import { Route as FreelancersIdRouteImport } from './routes/freelancers.$id'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPublicNotificationPushRouteImport } from './routes/api/public/notification-push'
import { Route as ApiPublicNotificationEmailRouteImport } from './routes/api/public/notification-email'
import { Route as ApiPublicCapacityAlertRouteImport } from './routes/api/public/capacity-alert'
import { Route as AuthenticatedDashboardTokensRouteImport } from './routes/_authenticated/dashboard.tokens'
import { Route as AuthenticatedDashboardTeamCalendarRouteImport } from './routes/_authenticated/dashboard.team-calendar'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard.profile'
import { Route as AuthenticatedDashboardPoolRouteImport } from './routes/_authenticated/dashboard.pool'
import { Route as AuthenticatedDashboardNotificationsRouteImport } from './routes/_authenticated/dashboard.notifications'
import { Route as AuthenticatedDashboardMatchesRouteImport } from './routes/_authenticated/dashboard.matches'
import { Route as AuthenticatedDashboardEngagementsRouteImport } from './routes/_authenticated/dashboard.engagements'
import { Route as AuthenticatedDashboardCalendarsRouteImport } from './routes/_authenticated/dashboard.calendars'
import { Route as AuthenticatedDashboardCalendarRouteImport } from './routes/_authenticated/dashboard.calendar'
import { Route as AuthenticatedAdminWikiRouteImport } from './routes/_authenticated/admin.wiki'
import { Route as AuthenticatedAdminTokensRouteImport } from './routes/_authenticated/admin.tokens'
import { Route as AuthenticatedAdminTestingRouteImport } from './routes/_authenticated/admin.testing'
import { Route as AuthenticatedAdminTeamsRouteImport } from './routes/_authenticated/admin.teams'
import { Route as AuthenticatedAdminReviewsRouteImport } from './routes/_authenticated/admin.reviews'
import { Route as AuthenticatedAdminPlatformRulesRouteImport } from './routes/_authenticated/admin.platform-rules'
import { Route as AuthenticatedAdminPitcallsRouteImport } from './routes/_authenticated/admin.pitcalls'
import { Route as AuthenticatedAdminPermissionsRouteImport } from './routes/_authenticated/admin.permissions'
import { Route as AuthenticatedAdminMatchingRouteImport } from './routes/_authenticated/admin.matching'
import { Route as AuthenticatedAdminLaunchRouteImport } from './routes/_authenticated/admin.launch'
import { Route as AuthenticatedAdminCalendarsRouteImport } from './routes/_authenticated/admin.calendars'
import { Route as AuthenticatedDashboardRequestsIndexRouteImport } from './routes/_authenticated/dashboard.requests.index'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as AuthenticatedDashboardRequestsNewRouteImport } from './routes/_authenticated/dashboard.requests.new'
import { Route as AuthenticatedDashboardRequestsIdMatchesRouteImport } from './routes/_authenticated/dashboard.requests.$id.matches'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIdRoute = TeamsIdRouteImport.update({
  id: '/teams/$id',
  path: '/teams/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalInfoRoute = LegalInfoRouteImport.update({
  id: '/legal/info',
  path: '/legal/info',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDocRoute = LegalDocRouteImport.update({
  id: '/legal/$doc',
  path: '/legal/$doc',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancersIdRoute = FreelancersIdRouteImport.update({
  id: '/freelancers/$id',
  path: '/freelancers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicNotificationPushRoute =
  ApiPublicNotificationPushRouteImport.update({
    id: '/api/public/notification-push',
    path: '/api/public/notification-push',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNotificationEmailRoute =
  ApiPublicNotificationEmailRouteImport.update({
    id: '/api/public/notification-email',
    path: '/api/public/notification-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCapacityAlertRoute = ApiPublicCapacityAlertRouteImport.update({
  id: '/api/public/capacity-alert',
  path: '/api/public/capacity-alert',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardTokensRoute =
  AuthenticatedDashboardTokensRouteImport.update({
    id: '/tokens',
    path: '/tokens',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTeamCalendarRoute =
  AuthenticatedDashboardTeamCalendarRouteImport.update({
    id: '/team-calendar',
    path: '/team-calendar',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPoolRoute =
  AuthenticatedDashboardPoolRouteImport.update({
    id: '/pool',
    path: '/pool',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardNotificationsRoute =
  AuthenticatedDashboardNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMatchesRoute =
  AuthenticatedDashboardMatchesRouteImport.update({
    id: '/matches',
    path: '/matches',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardEngagementsRoute =
  AuthenticatedDashboardEngagementsRouteImport.update({
    id: '/engagements',
    path: '/engagements',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCalendarsRoute =
  AuthenticatedDashboardCalendarsRouteImport.update({
    id: '/calendars',
    path: '/calendars',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCalendarRoute =
  AuthenticatedDashboardCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminWikiRoute = AuthenticatedAdminWikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTokensRoute =
  AuthenticatedAdminTokensRouteImport.update({
    id: '/tokens',
    path: '/tokens',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTestingRoute =
  AuthenticatedAdminTestingRouteImport.update({
    id: '/testing',
    path: '/testing',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTeamsRoute = AuthenticatedAdminTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminReviewsRoute =
  AuthenticatedAdminReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPlatformRulesRoute =
  AuthenticatedAdminPlatformRulesRouteImport.update({
    id: '/platform-rules',
    path: '/platform-rules',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPitcallsRoute =
  AuthenticatedAdminPitcallsRouteImport.update({
    id: '/pitcalls',
    path: '/pitcalls',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPermissionsRoute =
  AuthenticatedAdminPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMatchingRoute =
  AuthenticatedAdminMatchingRouteImport.update({
    id: '/matching',
    path: '/matching',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLaunchRoute =
  AuthenticatedAdminLaunchRouteImport.update({
    id: '/launch',
    path: '/launch',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCalendarsRoute =
  AuthenticatedAdminCalendarsRouteImport.update({
    id: '/calendars',
    path: '/calendars',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedDashboardRequestsIndexRoute =
  AuthenticatedDashboardRequestsIndexRouteImport.update({
    id: '/requests/',
    path: '/requests/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRequestsNewRoute =
  AuthenticatedDashboardRequestsNewRouteImport.update({
    id: '/requests/new',
    path: '/requests/new',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardRequestsIdMatchesRoute =
  AuthenticatedDashboardRequestsIdMatchesRouteImport.update({
    id: '/requests/$id/matches',
    path: '/requests/$id/matches',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/market': typeof MarketRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/freelancers/$id': typeof FreelancersIdRoute
  '/legal/$doc': typeof LegalDocRoute
  '/legal/info': typeof LegalInfoRoute
  '/teams/$id': typeof TeamsIdRoute
  '/admin/calendars': typeof AuthenticatedAdminCalendarsRoute
  '/admin/launch': typeof AuthenticatedAdminLaunchRoute
  '/admin/matching': typeof AuthenticatedAdminMatchingRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/pitcalls': typeof AuthenticatedAdminPitcallsRoute
  '/admin/platform-rules': typeof AuthenticatedAdminPlatformRulesRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/teams': typeof AuthenticatedAdminTeamsRoute
  '/admin/testing': typeof AuthenticatedAdminTestingRoute
  '/admin/tokens': typeof AuthenticatedAdminTokensRoute
  '/admin/wiki': typeof AuthenticatedAdminWikiRoute
  '/dashboard/calendar': typeof AuthenticatedDashboardCalendarRoute
  '/dashboard/calendars': typeof AuthenticatedDashboardCalendarsRoute
  '/dashboard/engagements': typeof AuthenticatedDashboardEngagementsRoute
  '/dashboard/matches': typeof AuthenticatedDashboardMatchesRoute
  '/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/dashboard/pool': typeof AuthenticatedDashboardPoolRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/team-calendar': typeof AuthenticatedDashboardTeamCalendarRoute
  '/dashboard/tokens': typeof AuthenticatedDashboardTokensRoute
  '/api/public/capacity-alert': typeof ApiPublicCapacityAlertRoute
  '/api/public/notification-email': typeof ApiPublicNotificationEmailRoute
  '/api/public/notification-push': typeof ApiPublicNotificationPushRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/requests/new': typeof AuthenticatedDashboardRequestsNewRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/dashboard/requests/': typeof AuthenticatedDashboardRequestsIndexRoute
  '/dashboard/requests/$id/matches': typeof AuthenticatedDashboardRequestsIdMatchesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/market': typeof MarketRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify-email': typeof VerifyEmailRoute
  '/freelancers/$id': typeof FreelancersIdRoute
  '/legal/$doc': typeof LegalDocRoute
  '/legal/info': typeof LegalInfoRoute
  '/teams/$id': typeof TeamsIdRoute
  '/admin/calendars': typeof AuthenticatedAdminCalendarsRoute
  '/admin/launch': typeof AuthenticatedAdminLaunchRoute
  '/admin/matching': typeof AuthenticatedAdminMatchingRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/pitcalls': typeof AuthenticatedAdminPitcallsRoute
  '/admin/platform-rules': typeof AuthenticatedAdminPlatformRulesRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/teams': typeof AuthenticatedAdminTeamsRoute
  '/admin/testing': typeof AuthenticatedAdminTestingRoute
  '/admin/tokens': typeof AuthenticatedAdminTokensRoute
  '/admin/wiki': typeof AuthenticatedAdminWikiRoute
  '/dashboard/calendar': typeof AuthenticatedDashboardCalendarRoute
  '/dashboard/calendars': typeof AuthenticatedDashboardCalendarsRoute
  '/dashboard/engagements': typeof AuthenticatedDashboardEngagementsRoute
  '/dashboard/matches': typeof AuthenticatedDashboardMatchesRoute
  '/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/dashboard/pool': typeof AuthenticatedDashboardPoolRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/team-calendar': typeof AuthenticatedDashboardTeamCalendarRoute
  '/dashboard/tokens': typeof AuthenticatedDashboardTokensRoute
  '/api/public/capacity-alert': typeof ApiPublicCapacityAlertRoute
  '/api/public/notification-email': typeof ApiPublicNotificationEmailRoute
  '/api/public/notification-push': typeof ApiPublicNotificationPushRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/requests/new': typeof AuthenticatedDashboardRequestsNewRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/dashboard/requests': typeof AuthenticatedDashboardRequestsIndexRoute
  '/dashboard/requests/$id/matches': typeof AuthenticatedDashboardRequestsIdMatchesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/market': typeof MarketRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/freelancers/$id': typeof FreelancersIdRoute
  '/legal/$doc': typeof LegalDocRoute
  '/legal/info': typeof LegalInfoRoute
  '/teams/$id': typeof TeamsIdRoute
  '/_authenticated/admin/calendars': typeof AuthenticatedAdminCalendarsRoute
  '/_authenticated/admin/launch': typeof AuthenticatedAdminLaunchRoute
  '/_authenticated/admin/matching': typeof AuthenticatedAdminMatchingRoute
  '/_authenticated/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/_authenticated/admin/pitcalls': typeof AuthenticatedAdminPitcallsRoute
  '/_authenticated/admin/platform-rules': typeof AuthenticatedAdminPlatformRulesRoute
  '/_authenticated/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/_authenticated/admin/teams': typeof AuthenticatedAdminTeamsRoute
  '/_authenticated/admin/testing': typeof AuthenticatedAdminTestingRoute
  '/_authenticated/admin/tokens': typeof AuthenticatedAdminTokensRoute
  '/_authenticated/admin/wiki': typeof AuthenticatedAdminWikiRoute
  '/_authenticated/dashboard/calendar': typeof AuthenticatedDashboardCalendarRoute
  '/_authenticated/dashboard/calendars': typeof AuthenticatedDashboardCalendarsRoute
  '/_authenticated/dashboard/engagements': typeof AuthenticatedDashboardEngagementsRoute
  '/_authenticated/dashboard/matches': typeof AuthenticatedDashboardMatchesRoute
  '/_authenticated/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/_authenticated/dashboard/pool': typeof AuthenticatedDashboardPoolRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/dashboard/team-calendar': typeof AuthenticatedDashboardTeamCalendarRoute
  '/_authenticated/dashboard/tokens': typeof AuthenticatedDashboardTokensRoute
  '/api/public/capacity-alert': typeof ApiPublicCapacityAlertRoute
  '/api/public/notification-email': typeof ApiPublicNotificationEmailRoute
  '/api/public/notification-push': typeof ApiPublicNotificationPushRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/requests/new': typeof AuthenticatedDashboardRequestsNewRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/_authenticated/dashboard/requests/': typeof AuthenticatedDashboardRequestsIndexRoute
  '/_authenticated/dashboard/requests/$id/matches': typeof AuthenticatedDashboardRequestsIdMatchesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/market'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/verify-email'
    | '/admin'
    | '/dashboard'
    | '/freelancers/$id'
    | '/legal/$doc'
    | '/legal/info'
    | '/teams/$id'
    | '/admin/calendars'
    | '/admin/launch'
    | '/admin/matching'
    | '/admin/permissions'
    | '/admin/pitcalls'
    | '/admin/platform-rules'
    | '/admin/reviews'
    | '/admin/teams'
    | '/admin/testing'
    | '/admin/tokens'
    | '/admin/wiki'
    | '/dashboard/calendar'
    | '/dashboard/calendars'
    | '/dashboard/engagements'
    | '/dashboard/matches'
    | '/dashboard/notifications'
    | '/dashboard/pool'
    | '/dashboard/profile'
    | '/dashboard/team-calendar'
    | '/dashboard/tokens'
    | '/api/public/capacity-alert'
    | '/api/public/notification-email'
    | '/api/public/notification-push'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/requests/new'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/dashboard/requests/'
    | '/dashboard/requests/$id/matches'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/market'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/verify-email'
    | '/freelancers/$id'
    | '/legal/$doc'
    | '/legal/info'
    | '/teams/$id'
    | '/admin/calendars'
    | '/admin/launch'
    | '/admin/matching'
    | '/admin/permissions'
    | '/admin/pitcalls'
    | '/admin/platform-rules'
    | '/admin/reviews'
    | '/admin/teams'
    | '/admin/testing'
    | '/admin/tokens'
    | '/admin/wiki'
    | '/dashboard/calendar'
    | '/dashboard/calendars'
    | '/dashboard/engagements'
    | '/dashboard/matches'
    | '/dashboard/notifications'
    | '/dashboard/pool'
    | '/dashboard/profile'
    | '/dashboard/team-calendar'
    | '/dashboard/tokens'
    | '/api/public/capacity-alert'
    | '/api/public/notification-email'
    | '/api/public/notification-push'
    | '/admin'
    | '/dashboard'
    | '/dashboard/requests/new'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/dashboard/requests'
    | '/dashboard/requests/$id/matches'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/market'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/verify-email'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/freelancers/$id'
    | '/legal/$doc'
    | '/legal/info'
    | '/teams/$id'
    | '/_authenticated/admin/calendars'
    | '/_authenticated/admin/launch'
    | '/_authenticated/admin/matching'
    | '/_authenticated/admin/permissions'
    | '/_authenticated/admin/pitcalls'
    | '/_authenticated/admin/platform-rules'
    | '/_authenticated/admin/reviews'
    | '/_authenticated/admin/teams'
    | '/_authenticated/admin/testing'
    | '/_authenticated/admin/tokens'
    | '/_authenticated/admin/wiki'
    | '/_authenticated/dashboard/calendar'
    | '/_authenticated/dashboard/calendars'
    | '/_authenticated/dashboard/engagements'
    | '/_authenticated/dashboard/matches'
    | '/_authenticated/dashboard/notifications'
    | '/_authenticated/dashboard/pool'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/team-calendar'
    | '/_authenticated/dashboard/tokens'
    | '/api/public/capacity-alert'
    | '/api/public/notification-email'
    | '/api/public/notification-push'
    | '/_authenticated/admin/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/requests/new'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/_authenticated/dashboard/requests/'
    | '/_authenticated/dashboard/requests/$id/matches'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  MarketRoute: typeof MarketRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  FreelancersIdRoute: typeof FreelancersIdRoute
  LegalDocRoute: typeof LegalDocRoute
  LegalInfoRoute: typeof LegalInfoRoute
  TeamsIdRoute: typeof TeamsIdRoute
  ApiPublicCapacityAlertRoute: typeof ApiPublicCapacityAlertRoute
  ApiPublicNotificationEmailRoute: typeof ApiPublicNotificationEmailRoute
  ApiPublicNotificationPushRoute: typeof ApiPublicNotificationPushRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$id': {
      id: '/teams/$id'
      path: '/teams/$id'
      fullPath: '/teams/$id'
      preLoaderRoute: typeof TeamsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/info': {
      id: '/legal/info'
      path: '/legal/info'
      fullPath: '/legal/info'
      preLoaderRoute: typeof LegalInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$doc': {
      id: '/legal/$doc'
      path: '/legal/$doc'
      fullPath: '/legal/$doc'
      preLoaderRoute: typeof LegalDocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelancers/$id': {
      id: '/freelancers/$id'
      path: '/freelancers/$id'
      fullPath: '/freelancers/$id'
      preLoaderRoute: typeof FreelancersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/notification-push': {
      id: '/api/public/notification-push'
      path: '/api/public/notification-push'
      fullPath: '/api/public/notification-push'
      preLoaderRoute: typeof ApiPublicNotificationPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notification-email': {
      id: '/api/public/notification-email'
      path: '/api/public/notification-email'
      fullPath: '/api/public/notification-email'
      preLoaderRoute: typeof ApiPublicNotificationEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/capacity-alert': {
      id: '/api/public/capacity-alert'
      path: '/api/public/capacity-alert'
      fullPath: '/api/public/capacity-alert'
      preLoaderRoute: typeof ApiPublicCapacityAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/tokens': {
      id: '/_authenticated/dashboard/tokens'
      path: '/tokens'
      fullPath: '/dashboard/tokens'
      preLoaderRoute: typeof AuthenticatedDashboardTokensRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/team-calendar': {
      id: '/_authenticated/dashboard/team-calendar'
      path: '/team-calendar'
      fullPath: '/dashboard/team-calendar'
      preLoaderRoute: typeof AuthenticatedDashboardTeamCalendarRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/pool': {
      id: '/_authenticated/dashboard/pool'
      path: '/pool'
      fullPath: '/dashboard/pool'
      preLoaderRoute: typeof AuthenticatedDashboardPoolRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/notifications': {
      id: '/_authenticated/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof AuthenticatedDashboardNotificationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/matches': {
      id: '/_authenticated/dashboard/matches'
      path: '/matches'
      fullPath: '/dashboard/matches'
      preLoaderRoute: typeof AuthenticatedDashboardMatchesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/engagements': {
      id: '/_authenticated/dashboard/engagements'
      path: '/engagements'
      fullPath: '/dashboard/engagements'
      preLoaderRoute: typeof AuthenticatedDashboardEngagementsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/calendars': {
      id: '/_authenticated/dashboard/calendars'
      path: '/calendars'
      fullPath: '/dashboard/calendars'
      preLoaderRoute: typeof AuthenticatedDashboardCalendarsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/calendar': {
      id: '/_authenticated/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof AuthenticatedDashboardCalendarRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin/wiki': {
      id: '/_authenticated/admin/wiki'
      path: '/wiki'
      fullPath: '/admin/wiki'
      preLoaderRoute: typeof AuthenticatedAdminWikiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tokens': {
      id: '/_authenticated/admin/tokens'
      path: '/tokens'
      fullPath: '/admin/tokens'
      preLoaderRoute: typeof AuthenticatedAdminTokensRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/testing': {
      id: '/_authenticated/admin/testing'
      path: '/testing'
      fullPath: '/admin/testing'
      preLoaderRoute: typeof AuthenticatedAdminTestingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/teams': {
      id: '/_authenticated/admin/teams'
      path: '/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AuthenticatedAdminTeamsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reviews': {
      id: '/_authenticated/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AuthenticatedAdminReviewsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/platform-rules': {
      id: '/_authenticated/admin/platform-rules'
      path: '/platform-rules'
      fullPath: '/admin/platform-rules'
      preLoaderRoute: typeof AuthenticatedAdminPlatformRulesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pitcalls': {
      id: '/_authenticated/admin/pitcalls'
      path: '/pitcalls'
      fullPath: '/admin/pitcalls'
      preLoaderRoute: typeof AuthenticatedAdminPitcallsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/permissions': {
      id: '/_authenticated/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AuthenticatedAdminPermissionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/matching': {
      id: '/_authenticated/admin/matching'
      path: '/matching'
      fullPath: '/admin/matching'
      preLoaderRoute: typeof AuthenticatedAdminMatchingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/launch': {
      id: '/_authenticated/admin/launch'
      path: '/launch'
      fullPath: '/admin/launch'
      preLoaderRoute: typeof AuthenticatedAdminLaunchRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/calendars': {
      id: '/_authenticated/admin/calendars'
      path: '/calendars'
      fullPath: '/admin/calendars'
      preLoaderRoute: typeof AuthenticatedAdminCalendarsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/dashboard/requests/': {
      id: '/_authenticated/dashboard/requests/'
      path: '/requests'
      fullPath: '/dashboard/requests/'
      preLoaderRoute: typeof AuthenticatedDashboardRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/requests/new': {
      id: '/_authenticated/dashboard/requests/new'
      path: '/requests/new'
      fullPath: '/dashboard/requests/new'
      preLoaderRoute: typeof AuthenticatedDashboardRequestsNewRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/requests/$id/matches': {
      id: '/_authenticated/dashboard/requests/$id/matches'
      path: '/requests/$id/matches'
      fullPath: '/dashboard/requests/$id/matches'
      preLoaderRoute: typeof AuthenticatedDashboardRequestsIdMatchesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCalendarsRoute: typeof AuthenticatedAdminCalendarsRoute
  AuthenticatedAdminLaunchRoute: typeof AuthenticatedAdminLaunchRoute
  AuthenticatedAdminMatchingRoute: typeof AuthenticatedAdminMatchingRoute
  AuthenticatedAdminPermissionsRoute: typeof AuthenticatedAdminPermissionsRoute
  AuthenticatedAdminPitcallsRoute: typeof AuthenticatedAdminPitcallsRoute
  AuthenticatedAdminPlatformRulesRoute: typeof AuthenticatedAdminPlatformRulesRoute
  AuthenticatedAdminReviewsRoute: typeof AuthenticatedAdminReviewsRoute
  AuthenticatedAdminTeamsRoute: typeof AuthenticatedAdminTeamsRoute
  AuthenticatedAdminTestingRoute: typeof AuthenticatedAdminTestingRoute
  AuthenticatedAdminTokensRoute: typeof AuthenticatedAdminTokensRoute
  AuthenticatedAdminWikiRoute: typeof AuthenticatedAdminWikiRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCalendarsRoute: AuthenticatedAdminCalendarsRoute,
  AuthenticatedAdminLaunchRoute: AuthenticatedAdminLaunchRoute,
  AuthenticatedAdminMatchingRoute: AuthenticatedAdminMatchingRoute,
  AuthenticatedAdminPermissionsRoute: AuthenticatedAdminPermissionsRoute,
  AuthenticatedAdminPitcallsRoute: AuthenticatedAdminPitcallsRoute,
  AuthenticatedAdminPlatformRulesRoute: AuthenticatedAdminPlatformRulesRoute,
  AuthenticatedAdminReviewsRoute: AuthenticatedAdminReviewsRoute,
  AuthenticatedAdminTeamsRoute: AuthenticatedAdminTeamsRoute,
  AuthenticatedAdminTestingRoute: AuthenticatedAdminTestingRoute,
  AuthenticatedAdminTokensRoute: AuthenticatedAdminTokensRoute,
  AuthenticatedAdminWikiRoute: AuthenticatedAdminWikiRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardCalendarRoute: typeof AuthenticatedDashboardCalendarRoute
  AuthenticatedDashboardCalendarsRoute: typeof AuthenticatedDashboardCalendarsRoute
  AuthenticatedDashboardEngagementsRoute: typeof AuthenticatedDashboardEngagementsRoute
  AuthenticatedDashboardMatchesRoute: typeof AuthenticatedDashboardMatchesRoute
  AuthenticatedDashboardNotificationsRoute: typeof AuthenticatedDashboardNotificationsRoute
  AuthenticatedDashboardPoolRoute: typeof AuthenticatedDashboardPoolRoute
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardTeamCalendarRoute: typeof AuthenticatedDashboardTeamCalendarRoute
  AuthenticatedDashboardTokensRoute: typeof AuthenticatedDashboardTokensRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardRequestsNewRoute: typeof AuthenticatedDashboardRequestsNewRoute
  AuthenticatedDashboardRequestsIndexRoute: typeof AuthenticatedDashboardRequestsIndexRoute
  AuthenticatedDashboardRequestsIdMatchesRoute: typeof AuthenticatedDashboardRequestsIdMatchesRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardCalendarRoute: AuthenticatedDashboardCalendarRoute,
    AuthenticatedDashboardCalendarsRoute: AuthenticatedDashboardCalendarsRoute,
    AuthenticatedDashboardEngagementsRoute:
      AuthenticatedDashboardEngagementsRoute,
    AuthenticatedDashboardMatchesRoute: AuthenticatedDashboardMatchesRoute,
    AuthenticatedDashboardNotificationsRoute:
      AuthenticatedDashboardNotificationsRoute,
    AuthenticatedDashboardPoolRoute: AuthenticatedDashboardPoolRoute,
    AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
    AuthenticatedDashboardTeamCalendarRoute:
      AuthenticatedDashboardTeamCalendarRoute,
    AuthenticatedDashboardTokensRoute: AuthenticatedDashboardTokensRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardRequestsNewRoute:
      AuthenticatedDashboardRequestsNewRoute,
    AuthenticatedDashboardRequestsIndexRoute:
      AuthenticatedDashboardRequestsIndexRoute,
    AuthenticatedDashboardRequestsIdMatchesRoute:
      AuthenticatedDashboardRequestsIdMatchesRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  MarketRoute: MarketRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  FreelancersIdRoute: FreelancersIdRoute,
  LegalDocRoute: LegalDocRoute,
  LegalInfoRoute: LegalInfoRoute,
  TeamsIdRoute: TeamsIdRoute,
  ApiPublicCapacityAlertRoute: ApiPublicCapacityAlertRoute,
  ApiPublicNotificationEmailRoute: ApiPublicNotificationEmailRoute,
  ApiPublicNotificationPushRoute: ApiPublicNotificationPushRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
