import type { DemoCity, DemoRound, DemoScenario } from "./types";
import { expandRanges } from "../anchor";

const MONZA: DemoCity = { city: "Monza", region: "Lombardia", country: "Italy", lat: 45.6156, lng: 9.2811 };
const IMOLA: DemoCity = { city: "Imola", region: "Emilia-Romagna", country: "Italy", lat: 44.3441, lng: 11.7161 };
const MODENA: DemoCity = { city: "Modena", region: "Emilia-Romagna", country: "Italy", lat: 44.6471, lng: 10.9252 };
const SILVERSTONE: DemoCity = { city: "Silverstone", region: "England", country: "United Kingdom", lat: 52.0733, lng: -1.0147 };
const LE_MANS: DemoCity = { city: "Le Mans", region: "Pays de la Loire", country: "France", lat: 47.9558, lng: 0.2075 };
const SUZUKA: DemoCity = { city: "Suzuka", region: "Mie", country: "Japan", lat: 34.8431, lng: 136.5407 };
const VALENCIA: DemoCity = { city: "Valencia", region: "Comunidad Valenciana", country: "Spain", lat: 39.4699, lng: -0.3763 };

const ENG_SKILLS = ["telemetry_analysis", "race_engineering", "motec_i2"];
const MECH_SKILLS = ["pit_stop_crew", "tyre_management", "brake_specialist"];

// Scenario D — the 2027 season exactly as in PITCALL_DEMO_GT3_EUROPE_2027.ics
// (all-day events, DTEND exclusive → inclusive end shown here). 8 rounds × 4 days = 32 days.
export const SEASON_2027_FILE = "PITCALL_DEMO_GT3_EUROPE_2027.ics";
export const SEASON_2027_ROUNDS: DemoRound[] = [
  { label: "Round 1", start: "2027-03-18", end: "2027-03-21" },
  { label: "Round 2", start: "2027-04-22", end: "2027-04-25" },
  { label: "Round 3", start: "2027-05-27", end: "2027-05-30" },
  { label: "Round 4", start: "2027-07-01", end: "2027-07-04" },
  { label: "Round 5", start: "2027-08-05", end: "2027-08-08" },
  { label: "Round 6", start: "2027-09-09", end: "2027-09-12" },
  { label: "Round 7", start: "2027-10-14", end: "2027-10-17" },
  { label: "Round 8", start: "2027-11-11", end: "2027-11-14" },
];
const SEASON_2027_DAYS = expandRanges(SEASON_2027_ROUNDS); // 32
const SEASON_2027_MINUS_R8 = expandRanges(SEASON_2027_ROUNDS.slice(0, 7)); // 28 → missing 12.5% ≤ 20% (Partial)
const SEASON_2027_R1_R5 = expandRanges(SEASON_2027_ROUNDS.slice(0, 5)); // 20 → missing 37.5% > 20% (excluded)

export const DEMO_V1: DemoScenario = {
  id: "v1",
  version: "1.0.0",
  title: { it: "DEMO V1 — Race weekend GT3", en: "DEMO V1 — GT3 race weekend" },
  description: {
    it: "Cast ridotto e intenzionale per mostrare Preview, Full/Partial, relevance, Availability Opportunity, Pool, Engagement e SOS con il motore reale PITCALL.",
    en: "Small, intentional cast that shows Preview, Full/Partial, relevance, Availability Opportunity, Pool, Engagement and SOS on the real PITCALL engine.",
  },

  teams: [
    {
      key: "apex",
      team_name: "DEMO Apex Racing",
      initials: "AR",
      team_type: "private_team",
      primary_discipline: "gt3",
      founded_year: 2009,
      size: "11-50",
      city: MONZA,
      bio: {
        it: "Team GT3 con base a Monza. Nucleo fisso ridotto, allargato con freelance sui weekend gara.",
        en: "GT3 team based in Monza. Small permanent core, expanded with freelancers on race weekends.",
      },
      tokens: 300,
      role_in_demo: { it: "Team protagonista della demo", en: "Main demo team" },
    },
    {
      key: "nordic",
      team_name: "DEMO Nordic Motorsport",
      initials: "NM",
      team_type: "engineering_company",
      primary_discipline: "gt3",
      founded_year: 2015,
      size: "1-10",
      city: SILVERSTONE,
      bio: {
        it: "Struttura di ingegneria con base a Silverstone, usata come secondo team per confronti.",
        en: "Engineering outfit based in Silverstone, used as the second team for comparisons.",
      },
      tokens: 200,
      role_in_demo: { it: "Secondo team (confronto)", en: "Second team (comparison)" },
    },
  ],

  freelancers: [
    {
      key: "mario",
      first_name: "DEMO Mario",
      last_name: "Bellini",
      role_group: "engineering",
      sub_roles: [{ sub_role: "race_engineer", level: "senior" }],
      disciplines: ["gt3", "wec_hypercar"],
      skills: [...ENG_SKILLS, "strategy_engineer", "data_acquisition"],
      languages: [
        { code: "it", level: "native" },
        { code: "en", level: "fluent" },
      ],
      experiences: [{ discipline: "gt3", years: 12 }],
      day_rate: 550,
      years_experience: 14,
      travels: true,
      city: MONZA,
      headline: { it: "Race Engineer GT3 senior · 14 stagioni", en: "Senior GT3 race engineer · 14 seasons" },
      availability: [7, 8, 9, 14, 15, 16],
      role_in_demo: { it: "Full Match forte (top ranking)", en: "Strong Full Match (top ranked)" },
      pool_of: ["apex"],
    },
    {
      key: "gianni",
      first_name: "DEMO Gianni",
      last_name: "Ferraro",
      role_group: "engineering",
      sub_roles: [{ sub_role: "race_engineer", level: "intermediate" }],
      disciplines: ["f4_italian"],
      skills: ["race_engineering", "python_data"],
      languages: [{ code: "en", level: "advanced" }],
      experiences: [{ discipline: "f4_italian", years: 5 }],
      day_rate: 800,
      years_experience: 6,
      travels: true,
      city: SILVERSTONE,
      headline: { it: "Race Engineer formula, tariffa alta", en: "Formula race engineer, high day rate" },
      availability: [7, 8, 9],
      role_in_demo: { it: "Full Match con relevance più bassa", en: "Full Match with lower relevance" },
    },
    {
      key: "anna",
      first_name: "DEMO Anna",
      last_name: "Ricci",
      role_group: "engineering",
      sub_roles: [{ sub_role: "race_engineer", level: "senior" }],
      disciplines: ["gt3"],
      skills: ["telemetry_analysis", "race_engineering", "data_acquisition"],
      languages: [
        { code: "it", level: "native" },
        { code: "en", level: "fluent" },
      ],
      experiences: [{ discipline: "gt3", years: 9 }],
      day_rate: 600,
      years_experience: 10,
      travels: true,
      city: IMOLA,
      headline: { it: "Race Engineer GT3, disponibilità parziale", en: "GT3 race engineer, partial availability" },
      availability: [7, 8, 14, 15, 16],
      role_in_demo: { it: "Partial Match valido (copertura 2/3)", en: "Valid Partial Match (2 of 3 days)" },
    },
    {
      key: "luca",
      first_name: "DEMO Luca",
      last_name: "Moretti",
      role_group: "engineering",
      sub_roles: [{ sub_role: "design_engineer", level: "senior" }],
      disciplines: ["gt3"],
      skills: ["telemetry_analysis", "catia", "fea"],
      languages: [{ code: "en", level: "basic" }],
      experiences: [{ discipline: "gt3", years: 7 }],
      day_rate: 500,
      years_experience: 8,
      travels: true,
      city: SUZUKA,
      headline: { it: "Design Engineer, profilo distante dal ruolo richiesto", en: "Design engineer, far from the requested role" },
      availability: [7, 8, 9],
      role_in_demo: {
        it: "Full Match con relevance <50% — DEVE restare visibile",
        en: "Full Match below 50% relevance — MUST stay visible",
      },
    },
    {
      key: "pierre",
      first_name: "DEMO Pierre",
      last_name: "Laurent",
      role_group: "engineering",
      sub_roles: [{ sub_role: "race_engineer", level: "senior" }],
      disciplines: ["gt3", "lmp2"],
      skills: [...ENG_SKILLS, "strategy_engineer"],
      languages: [
        { code: "fr", level: "native" },
        { code: "en", level: "fluent" },
      ],
      experiences: [{ discipline: "gt3", years: 11 }],
      day_rate: 520,
      years_experience: 12,
      travels: true,
      city: LE_MANS,
      headline: { it: "Race Engineer senza disponibilità sulle date", en: "Race engineer with no availability on the dates" },
      availability: [35, 36, 37],
      role_in_demo: { it: "Candidato Availability Opportunity", en: "Availability Opportunity candidate" },
    },
    {
      key: "sofia",
      first_name: "DEMO Sofia",
      last_name: "Marchetti",
      role_group: "mechanics",
      sub_roles: [{ sub_role: "race_mechanic", level: "senior" }],
      disciplines: ["gt3"],
      skills: MECH_SKILLS,
      languages: [
        { code: "it", level: "native" },
        { code: "en", level: "advanced" },
      ],
      experiences: [{ discipline: "gt3", years: 8 }],
      day_rate: 400,
      years_experience: 9,
      travels: true,
      city: MONZA,
      headline: { it: "Race Mechanic GT3 nel pool di Apex", en: "GT3 race mechanic inside the Apex pool" },
      availability: [14, 15, 16],
      role_in_demo: { it: "Membro del Pool di Apex", en: "Member of the Apex pool" },
      pool_of: ["apex"],
    },
    {
      key: "marta",
      first_name: "DEMO Marta",
      last_name: "Colombo",
      role_group: "mechanics",
      sub_roles: [{ sub_role: "race_mechanic", level: "senior" }],
      disciplines: ["gt3"],
      skills: MECH_SKILLS,
      languages: [
        { code: "it", level: "native" },
        { code: "en", level: "advanced" },
      ],
      experiences: [{ discipline: "gt3", years: 8 }],
      day_rate: 420,
      years_experience: 9,
      travels: true,
      city: MODENA,
      headline: { it: "Race Mechanic GT3 fuori dal pool", en: "GT3 race mechanic outside the pool" },
      availability: [14, 15, 16],
      role_in_demo: { it: "Controprova: fuori dal Pool", en: "Control case: outside the pool" },
    },
    {
      key: "karl",
      first_name: "DEMO Karl",
      last_name: "Brenner",
      role_group: "engineering",
      sub_roles: [{ sub_role: "race_engineer", level: "senior" }],
      disciplines: ["gt3"],
      skills: [...ENG_SKILLS],
      languages: [
        { code: "de", level: "native" },
        { code: "en", level: "fluent" },
      ],
      experiences: [{ discipline: "gt3", years: 10 }],
      day_rate: 500,
      years_experience: 11,
      travels: true,
      city: MONZA,
      headline: { it: "Race Engineer disponibile oggi (standby SOS)", en: "Race engineer available today (SOS standby)" },
      availability: ["today"],
      role_in_demo: { it: "Standby SOS", en: "SOS standby" },
    },
    {
      key: "dario",
      first_name: "DEMO Dario",
      last_name: "Esposito",
      role_group: "engineering",
      sub_roles: [{ sub_role: "race_engineer", level: "intermediate" }],
      disciplines: ["gt3"],
      skills: ["race_engineering", "telemetry_analysis"],
      languages: [{ code: "it", level: "native" }],
      experiences: [{ discipline: "gt3", years: 4 }],
      day_rate: 450,
      years_experience: 5,
      travels: true,
      city: MONZA,
      headline: { it: "Race Engineer che ha rinunciato all'ultimo", en: "Race engineer who pulled out at the last minute" },
      availability: ["today"],
      role_in_demo: { it: "No-show dello scenario SOS", en: "No-show of the SOS scenario" },
    },
    {
      key: "elena",
      first_name: "DEMO Elena",
      last_name: "Conti",
      role_group: "engineering",
      sub_roles: [{ sub_role: "race_engineer", level: "senior" }],
      disciplines: ["gt3"],
      skills: [...ENG_SKILLS, "strategy_engineer"],
      languages: [
        { code: "it", level: "native" },
        { code: "en", level: "fluent" },
      ],
      experiences: [{ discipline: "gt3", years: 10 }],
      day_rate: 520,
      years_experience: 11,
      travels: true,
      city: MONZA,
      headline: { it: "Race Engineer GT3 libera per tutta la stagione 2027", en: "GT3 race engineer free for the whole 2027 season" },
      availability: SEASON_2027_DAYS,
      role_in_demo: { it: "Scenario D — Full Match stagione (32/32 giorni)", en: "Scenario D — season Full Match (32/32 days)" },
    },
    {
      key: "tomas",
      first_name: "DEMO Tomas",
      last_name: "Weber",
      role_group: "engineering",
      sub_roles: [{ sub_role: "race_engineer", level: "senior" }],
      disciplines: ["gt3"],
      skills: [...ENG_SKILLS],
      languages: [
        { code: "de", level: "native" },
        { code: "en", level: "fluent" },
      ],
      experiences: [{ discipline: "gt3", years: 8 }],
      day_rate: 500,
      years_experience: 9,
      travels: true,
      city: IMOLA,
      headline: { it: "Race Engineer GT3, manca all'ultimo round 2027", en: "GT3 race engineer, missing the last 2027 round" },
      availability: SEASON_2027_MINUS_R8,
      role_in_demo: { it: "Scenario D — Partial Match stagione (28/32, −12,5%)", en: "Scenario D — season Partial Match (28/32, −12.5%)" },
    },
    {
      key: "hugo",
      first_name: "DEMO Hugo",
      last_name: "Navarro",
      role_group: "engineering",
      sub_roles: [{ sub_role: "race_engineer", level: "senior" }],
      disciplines: ["gt3"],
      skills: [...ENG_SKILLS],
      languages: [
        { code: "es", level: "native" },
        { code: "en", level: "fluent" },
      ],
      experiences: [{ discipline: "gt3", years: 7 }],
      day_rate: 480,
      years_experience: 8,
      travels: true,
      city: VALENCIA,
      headline: { it: "Race Engineer GT3 libero solo per metà stagione 2027", en: "GT3 race engineer free for half the 2027 season only" },
      availability: SEASON_2027_R1_R5,
      role_in_demo: { it: "Scenario D — escluso: copre solo i Round 1–5 (−37,5%)", en: "Scenario D — excluded: covers Rounds 1–5 only (−37.5%)" },
    },
    {
      key: "nadia",
      first_name: "DEMO Nadia",
      last_name: "Ferri",
      role_group: "engineering",
      sub_roles: [{ sub_role: "race_engineer", level: "intermediate" }],
      disciplines: ["gt4"],
      skills: ["race_engineering"],
      languages: [{ code: "it", level: "native" }],
      experiences: [{ discipline: "gt4", years: 3 }],
      day_rate: 380,
      years_experience: 3,
      travels: true,
      city: MODENA,
      headline: { it: "Race Engineer junior GT4, libera per tutta la stagione 2027", en: "Junior GT4 race engineer, free for the whole 2027 season" },
      availability: SEASON_2027_DAYS,
      role_in_demo: { it: "Scenario D — Full 32/32 ma relevance nettamente inferiore", en: "Scenario D — Full 32/32 but clearly lower relevance" },
    },
  ],

  canonicalPitCalls: [
    {
      key: "A",
      team: "apex",
      title: { it: "Scenario A — Standard / happy path", en: "Scenario A — Standard / happy path" },
      narrative: {
        it: "Pit Call creata dal vivo: Preview, pubblicazione, Full e Partial, ranking, relevance diverse, Request Confirmation, Engagement e blocco calendario.",
        en: "Pit Call created live: Preview, publish, Full and Partial, ranking, different relevance, Request Confirmation, Engagement and calendar blocking.",
      },
      input: {
        role_group: "engineering",
        sub_role: "race_engineer",
        sub_role_min_level: "intermediate",
        sub_role_hard: false,
        role_hard: true,
        discipline: "gt3",
        duration: "race_weekend",
        search_mode: "standard",
        days: [7, 8, 9],
        skills: ENG_SKILLS,
        skills_hard: [],
        languages: [{ code: "en", level: "advanced", hard: false }],
        budget_min: 400,
        budget_max: 700,
        travel_required: true,
        location: MONZA,
        location_relevance: "relevant",
        location_radius_km: 500,
      },
      expected: {
        full: ["mario", "gianni", "luca"],
        partial: ["anna"],
        absent: ["pierre", "sofia", "marta", "karl", "elena", "tomas", "hugo"],
        ranking: ["mario", "anna", "gianni", "luca"],
        min_score: { mario: 85 },
        max_score: { luca: 49.99 },
        visible_below_threshold: ["luca"],
      },
      steps: [
        { it: "Accedi come DEMO Apex Racing e apri Nuova Pit Call.", en: "Sign in as DEMO Apex Racing and open New Pit Call." },
        { it: "Inserisci gli input elencati qui sotto e guarda la Preview.", en: "Enter the inputs listed below and look at the Preview." },
        { it: "Pubblica la Pit Call: entra nella review window reale (5 minuti).", en: "Publish the Pit Call: it enters the real 5-minute review window." },
        { it: "Dall'ACP esegui il runner “Attiva Pit Call in review” per non aspettare.", en: "From the ACP run the “Activate pending reviews” runner instead of waiting." },
        { it: "Apri i Match Results: verifica Full, Partial, ranking e il match <50% visibile.", en: "Open Match Results: check Full, Partial, ranking and the visible sub-50% match." },
        { it: "Invia la Request Confirmation a DEMO Mario.", en: "Send the Request Confirmation to DEMO Mario." },
        { it: "Nella finestra del freelancer accetta: nasce l'Engagement e i giorni si bloccano a calendario.", en: "In the freelancer window accept it: the Engagement is created and the days get blocked in the calendar." },
      ],
    },
    {
      key: "B",
      team: "apex",
      title: { it: "Scenario B — Zero coverage → Availability Opportunity", en: "Scenario B — Zero coverage → Availability Opportunity" },
      narrative: {
        it: "Pit Call su date senza nessun professionista disponibile: PITCALL avvisa i profili rilevanti e il match nasce quando la disponibilità cambia.",
        en: "Pit Call on dates nobody is available for: PITCALL notifies the relevant profiles and the match appears once availability changes.",
      },
      input: {
        role_group: "engineering",
        sub_role: "race_engineer",
        sub_role_min_level: "senior",
        sub_role_hard: false,
        role_hard: true,
        discipline: "gt3",
        duration: "race_weekend",
        search_mode: "standard",
        days: [21, 22, 23],
        skills: ENG_SKILLS,
        skills_hard: [],
        languages: [],
        budget_min: 400,
        budget_max: 700,
        travel_required: true,
        location: LE_MANS,
        location_relevance: "relevant",
        location_radius_km: 500,
      },
      expected: {
        full: [],
        partial: [],
        absent: ["mario", "anna", "gianni", "luca", "pierre", "karl", "sofia", "marta", "elena", "tomas", "hugo"],
      },
      steps: [
        { it: "Crea la Pit Call dal vivo con gli input qui sotto.", en: "Create the Pit Call live with the inputs below." },
        { it: "Attivala con il runner “Attiva Pit Call in review”.", en: "Activate it with the “Activate pending reviews” runner." },
        { it: "Nessun match: esegui il runner “Availability Opportunity”.", en: "No matches: run the “Availability Opportunity” runner." },
        { it: "Impersona DEMO Pierre: nel Notification Center trova l'opportunità.", en: "Impersonate DEMO Pierre: the opportunity is in the Notification Center." },
        { it: "Aggiungi a calendario le date indicate e salva.", en: "Add the listed dates to the calendar and save." },
        { it: "Dall'ACP esegui “Svuota coda disponibilità”.", en: "From the ACP run “Drain availability queue”." },
        { it: "Torna sul team: il nuovo Full Match di Pierre è nei risultati.", en: "Back on the team side: Pierre's new Full Match is in the results." },
      ],
    },
    {
      key: "C",
      team: "apex",
      title: { it: "Scenario C — My Pool", en: "Scenario C — My Pool" },
      narrative: {
        it: "Pit Call in modalità Pool: solo i professionisti già fidati del team entrano nei risultati.",
        en: "Pool-mode Pit Call: only the team's trusted professionals show up in the results.",
      },
      input: {
        role_group: "mechanics",
        sub_role: "race_mechanic",
        sub_role_min_level: "intermediate",
        sub_role_hard: false,
        role_hard: true,
        discipline: "gt3",
        duration: "race_weekend",
        search_mode: "pool",
        days: [14, 15, 16],
        skills: MECH_SKILLS,
        skills_hard: [],
        languages: [],
        budget_min: 300,
        budget_max: 600,
        travel_required: true,
        location: MONZA,
        location_relevance: "relevant",
        location_radius_km: 500,
      },
      expected: {
        full: ["sofia"],
        absent: ["marta"],
      },
      steps: [
        { it: "Come DEMO Apex Racing crea una Pit Call scegliendo “Cerca nel mio Pool”.", en: "As DEMO Apex Racing create a Pit Call choosing “Search my Pool”." },
        { it: "Attivala con il runner “Attiva Pit Call in review”.", en: "Activate it with the “Activate pending reviews” runner." },
        { it: "Nei risultati compare DEMO Sofia (nel pool) e non DEMO Marta (fuori dal pool).", en: "Results show DEMO Sofia (in the pool) and not DEMO Marta (outside the pool)." },
      ],
    },
    {
      key: "D",
      team: "apex",
      title: { it: "Scenario D — Intera stagione 2027 (upload ICS)", en: "Scenario D — Full 2027 season (ICS upload)" },
      narrative: {
        it: "Pit Call di intera stagione creata dal vivo caricando il file ICS del campionato: 8 round, 32 giorni. Mostra Full/Partial su una stagione (Partial ammesso fino al 20% di giorni mancanti) e l'esclusione di chi copre troppo poco.",
        en: "Full-season Pit Call created live by uploading the championship ICS file: 8 rounds, 32 days. Shows Full/Partial over a season (Partial allowed up to 20% missing days) and the exclusion of anyone covering too little.",
      },
      ics: { filename: SEASON_2027_FILE, rounds: SEASON_2027_ROUNDS },
      input: {
        role_group: "engineering",
        sub_role: "race_engineer",
        sub_role_min_level: "intermediate",
        sub_role_hard: false,
        role_hard: true,
        discipline: "gt3",
        duration: "full_season",
        search_mode: "standard",
        days: SEASON_2027_DAYS,
        skills: ENG_SKILLS,
        skills_hard: [],
        languages: [{ code: "en", level: "advanced", hard: false }],
        budget_min: 30000,
        budget_max: 45000,
        travel_required: true,
        location: MONZA,
        location_relevance: "relevant",
        location_radius_km: 500,
      },
      expected: {
        full: ["elena"],
        partial: ["tomas"],
        absent: ["hugo", "mario", "anna", "gianni", "luca", "pierre", "karl", "dario", "sofia", "marta"],
        ranking: ["elena", "tomas"],
      },
      steps: [
        { it: "Accedi come DEMO Apex Racing, apri Nuova Pit Call e scegli durata “Intera stagione”.", en: "Sign in as DEMO Apex Racing, open New Pit Call and choose “Full season”." },
        { it: "Nei giorni di lavoro della stagione usa “Importa file .ics” e carica PITCALL_DEMO_GT3_EUROPE_2027.ics (scaricabile qui sotto): 32 giorni selezionati.", en: "In the season working days use “Import .ics” and upload PITCALL_DEMO_GT3_EUROPE_2027.ics (downloadable below): 32 days selected." },
        { it: "Inserisci gli altri input elencati e pubblica; attiva con il runner “Attiva Pit Call in review”.", en: "Enter the other listed inputs and publish; activate with the “Activate pending reviews” runner." },
        { it: "Match Results: DEMO Elena è Full (32/32), DEMO Tomas è Partial (manca il Round 8, 4 giorni = 12,5%).", en: "Match Results: DEMO Elena is Full (32/32), DEMO Tomas is Partial (Round 8 missing, 4 days = 12.5%)." },
        { it: "DEMO Hugo copre solo i Round 1–5 (12 giorni mancanti = 37,5% > 20%) e non compare.", en: "DEMO Hugo covers Rounds 1–5 only (12 days missing = 37.5% > 20%) and does not appear." },
      ],
    },
  ],

  preSeeded: {
    sos: {
      team: "apex",
      noShowFreelancer: "dario",
      standby: ["karl"],
      request: {
        title: { it: "GT3 — Race Engineer weekend Monza", en: "GT3 — Race engineer, Monza weekend" },
        role_group: "engineering",
        sub_role: "race_engineer",
        sub_role_min_level: "intermediate",
        discipline: "gt3",
        skills: ["race_engineering", "telemetry_analysis"],
        budget_min: 400,
        budget_max: 700,
        location: MONZA,
        location_radius_km: 500,
      },
      steps: [
        { it: "Accedi come DEMO Apex Racing e apri la Pit Call di oggi.", en: "Sign in as DEMO Apex Racing and open today's Pit Call." },
        { it: "DEMO Dario aveva confermato e ha poi rinunciato: la Pit Call è tornata attiva.", en: "DEMO Dario had confirmed and then pulled out: the Pit Call is active again." },
        { it: "Oggi è il primo giorno richiesto: compare l'azione SOS Call.", en: "Today is the first required day: the SOS Call action appears." },
        { it: "Lancia la SOS Call: DEMO Karl riceve la chiamata nel Notification Center.", en: "Fire the SOS Call: DEMO Karl gets it in the Notification Center." },
      ],
    },
    pool: {
      team: "apex",
      members: ["mario", "sofia"],
      steps: [
        { it: "Il pool di DEMO Apex Racing è già popolato dal seed.", en: "The DEMO Apex Racing pool is already populated by the seed." },
      ],
    },
  },

  availabilityOpportunity: {
    pitCall: "B",
    freelancer: "pierre",
    addDays: [21, 22, 23],
    steps: [],
  },
};
